spring:
  application:
    name: mdong_prac
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&connectionCollation=utf8mb4_unicode_ci&characterSetResults=utf8mb4&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
        globally_quoted_identifiers: true
        format_sql: true
        hbm2ddl:
          charset_name: utf8mb4
        connection.CharSet: utf8mb4
        connection.characterEncoding: utf8mb4
        connection.useUnicode: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false

kakao:
  api:
    key: ab50dff36e8d6211a657f24a1e12a3c1

#메세지 형태로 오류내용 response에 담아 전달
server:
  port: 8080
  error:
    include-message: always

springdoc:
  swagger-ui:
    #swagger-ui ?? ?? ?? (???? /swagger-ui.html??)
    path: /swagger-ui.html
    #? api? ?? ?? ??(desc : ????)
    groups-order: desc
    #?? ?? ?? (alpha : ??? ?? ??)
    tags-sorter: alpha
    #controller ?? ?? (method : delete - get - patch - post - put ? ??)
    operations-sorter: method
    #swagger-ui? ??? url? petstore html? ?? ????
    disable-swagger-default-url: true
    #swagger-ui?? try ?, request duration(api ?? ? ?? ??)? ???? ??
    display-request-duration: true
  #openAPI ?? ?? (default ?: /v3/api-docs) -> swagger? api ??? ?? ?? ??? ?????, openAPI? api?? ??? ? ??? ???.
  api-docs:
    path: /api-docs
  #"spring Actuator? endpoint"(-> ???? ? ??? api)?? ??? ???? ?? ??
  show-actuator: true
  #request media type? ?? ?
  default-consumes-media-type: application/json
  #response media type? ?? ?
  default-produces-media-type: application/json
  #?? ?? endpoint? ?? controller? swagger-ui? ????.
  paths-to-match:
    - /api/**


logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE